module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V1.Route
import Evergreen.V1.Types
import Evergreen.V6.Route
import Evergreen.V6.Types exposing (FrontendMsg(..), Theme(..), ToBackend(..), ToFrontend(..))
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V1.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V1.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V1.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V1.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V1.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V1.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V1.Types.BackendModel -> Evergreen.V6.Types.BackendModel
migrate_Types_BackendModel old =
    { leftSideRatio = 0
    , rightSideRatio = 0
    , range = 100
    , avatarScale = old.avatarScale
    , fankadeliSide = old.fankadeliSide |> migrate_Types_Side
    , theme = Light
    }


migrate_Types_FrontendModel : Evergreen.V1.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> Maybe.map migrate_Route_Route
    , leftSideRatio = 0
    , rightSideRatio = 0
    , range = 100
    , avatarScale = old.avatarScale
    , fankadeliSide = old.fankadeliSide |> migrate_Types_Side
    , theme = Light
    , clientId = old.clientId
    }


migrate_Route_Route : Evergreen.V1.Route.Route -> Evergreen.V6.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V1.Route.AdminPanel ->
            Evergreen.V6.Route.AdminPanel


migrate_Types_FrontendMsg : Evergreen.V1.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V1.Types.UrlChanged p0 ->
            Evergreen.V6.Types.UrlChanged p0

        Evergreen.V1.Types.Increment ->
            FNoop

        Evergreen.V1.Types.Decrement ->
            FNoop

        Evergreen.V1.Types.IncrementAmountChange p0 ->
            FNoop

        Evergreen.V1.Types.IsCenterLineVisibleChange p0 ->
            FNoop

        Evergreen.V1.Types.AvatarScaleChange p0 ->
            Evergreen.V6.Types.AvatarScaleChange p0

        Evergreen.V1.Types.FankaDeliSideChange p0 ->
            Evergreen.V6.Types.FankaDeliSideChange

        Evergreen.V1.Types.ResetSplitRatioButtonTap ->
            FNoop

        Evergreen.V1.Types.FNoop ->
            Evergreen.V6.Types.FNoop


migrate_Types_Side : Evergreen.V1.Types.Side -> Evergreen.V6.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V1.Types.Left ->
            Evergreen.V6.Types.Left

        Evergreen.V1.Types.Right ->
            Evergreen.V6.Types.Right


migrate_Types_ToBackend : Evergreen.V1.Types.ToBackend -> Evergreen.V6.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V1.Types.SplitRatioChanged p0 ->
            TBNoop

        Evergreen.V1.Types.IncrementAmountChanged p0 ->
            TBNoop

        Evergreen.V1.Types.IsCenterLineVisibleChanged p0 ->
            TBNoop

        Evergreen.V1.Types.AvatarScaleChanged p0 ->
            Evergreen.V6.Types.AvatarScaleChanged p0

        Evergreen.V1.Types.FankaDeliSideChanged p0 p1 ->
            Evergreen.V6.Types.FankaDeliSideChanged (p0 |> migrate_Types_Side)


migrate_Types_ToFrontend : Evergreen.V1.Types.ToFrontend -> Evergreen.V6.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V1.Types.SplitRatioNewValue p0 p1 ->
            TFNoop

        Evergreen.V1.Types.IncrementAmountNewValue p0 p1 ->
            TFNoop

        Evergreen.V1.Types.IsCenterLineVisibleNewValue p0 p1 ->
            TFNoop

        Evergreen.V1.Types.AvatarScaleNewValue p0 p1 ->
            Evergreen.V6.Types.AvatarScaleNewValue p0 p1

        Evergreen.V1.Types.FankadeliSideNewValue p0 p1 p2 ->
            TFNoop
