module Evergreen.Migrate.V7 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V6.Route
import Evergreen.V6.Types
import Evergreen.V7.Route
import Evergreen.V7.Types exposing (Theme(..))
import Lamdera.Migrations exposing (..)
import Maybe


frontendModel : Evergreen.V6.Types.FrontendModel -> ModelMigration Evergreen.V7.Types.FrontendModel Evergreen.V7.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V6.Types.BackendModel -> ModelMigration Evergreen.V7.Types.BackendModel Evergreen.V7.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V6.Types.FrontendMsg -> MsgMigration Evergreen.V7.Types.FrontendMsg Evergreen.V7.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V6.Types.ToBackend -> MsgMigration Evergreen.V7.Types.ToBackend Evergreen.V7.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V6.Types.BackendMsg -> MsgMigration Evergreen.V7.Types.BackendMsg Evergreen.V7.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V6.Types.ToFrontend -> MsgMigration Evergreen.V7.Types.ToFrontend Evergreen.V7.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V6.Types.BackendModel -> Evergreen.V7.Types.BackendModel
migrate_Types_BackendModel old =
    { leftSideRatio = old.leftSideRatio
    , rightSideRatio = old.rightSideRatio
    , range = old.range
    , avatarScale = old.avatarScale
    , fankadeliSide = old.fankadeliSide |> migrate_Types_Side
    , homeTheme = old.theme |> migrate_Types_Theme
    , adminTheme = Light
    }


migrate_Types_FrontendModel : Evergreen.V6.Types.FrontendModel -> Evergreen.V7.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , currentRoute = old.currentRoute |> Maybe.map migrate_Route_Route
    , leftSideRatio = old.leftSideRatio
    , rightSideRatio = old.rightSideRatio
    , range = old.range
    , avatarScale = old.avatarScale
    , fankadeliSide = old.fankadeliSide |> migrate_Types_Side
    , homeTheme = Light
    , adminTheme = Light
    , isAdminVisibleOnHomePage = False
    , clientId = old.clientId
    }


migrate_Route_Route : Evergreen.V6.Route.Route -> Evergreen.V7.Route.Route
migrate_Route_Route old =
    case old of
        Evergreen.V6.Route.AdminPanel ->
            Evergreen.V7.Route.AdminPanel


migrate_Types_FrontendMsg : Evergreen.V6.Types.FrontendMsg -> Evergreen.V7.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V6.Types.UrlChanged p0 ->
            Evergreen.V7.Types.UrlChanged p0

        Evergreen.V6.Types.IncrementLeftSideRatio ->
            Evergreen.V7.Types.IncrementLeftSideRatio

        Evergreen.V6.Types.DecrementLeftSideRatio ->
            Evergreen.V7.Types.DecrementLeftSideRatio

        Evergreen.V6.Types.IncrementRightSideRatio ->
            Evergreen.V7.Types.IncrementRightSideRatio

        Evergreen.V6.Types.DecrementRightSideRatio ->
            Evergreen.V7.Types.DecrementRightSideRatio

        Evergreen.V6.Types.RangeChange p0 ->
            Evergreen.V7.Types.RangeChange p0

        Evergreen.V6.Types.AvatarScaleChange p0 ->
            Evergreen.V7.Types.AvatarScaleChange p0

        Evergreen.V6.Types.FankaDeliSideChange ->
            Evergreen.V7.Types.FankaDeliSideChange

        Evergreen.V6.Types.ResetRatiosButtonTap ->
            Evergreen.V7.Types.ResetRatiosButtonTap

        Evergreen.V6.Types.LeftArrowKeyTap ->
            Evergreen.V7.Types.LeftArrowKeyTap

        Evergreen.V6.Types.RightArrowKeyTap ->
            Evergreen.V7.Types.RightArrowKeyTap

        Evergreen.V6.Types.ShiftLeftArrowKeyTap ->
            Evergreen.V7.Types.ShiftLeftArrowKeyTap

        Evergreen.V6.Types.ShiftRightArrowKeyTap ->
            Evergreen.V7.Types.ShiftRightArrowKeyTap

        Evergreen.V6.Types.ThemeChange p0 ->
            Evergreen.V7.Types.HomeThemeChange (p0 |> migrate_Types_Theme)

        Evergreen.V6.Types.FNoop ->
            Evergreen.V7.Types.FNoop


migrate_Types_Side : Evergreen.V6.Types.Side -> Evergreen.V7.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V6.Types.Left ->
            Evergreen.V7.Types.Left

        Evergreen.V6.Types.Right ->
            Evergreen.V7.Types.Right


migrate_Types_Theme : Evergreen.V6.Types.Theme -> Evergreen.V7.Types.Theme
migrate_Types_Theme old =
    case old of
        Evergreen.V6.Types.Light ->
            Evergreen.V7.Types.Light

        Evergreen.V6.Types.Dark ->
            Evergreen.V7.Types.Dark


migrate_Types_ToBackend : Evergreen.V6.Types.ToBackend -> Evergreen.V7.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V6.Types.LeftSideRatioChanged p0 ->
            Evergreen.V7.Types.LeftSideRatioChanged p0

        Evergreen.V6.Types.RightSideRatioChanged p0 ->
            Evergreen.V7.Types.RightSideRatioChanged p0

        Evergreen.V6.Types.RangeChanged p0 p1 p2 ->
            Evergreen.V7.Types.RangeChanged p0 p1 p2

        Evergreen.V6.Types.AvatarScaleChanged p0 ->
            Evergreen.V7.Types.AvatarScaleChanged p0

        Evergreen.V6.Types.FankaDeliSideChanged p0 ->
            Evergreen.V7.Types.FankaDeliSideChanged (p0 |> migrate_Types_Side)

        Evergreen.V6.Types.ResetRatiosButtonTapped p0 p1 ->
            Evergreen.V7.Types.ResetRatiosButtonTapped p0 p1

        Evergreen.V6.Types.ThemeChanged p0 ->
            Evergreen.V7.Types.HomeThemeChanged (p0 |> migrate_Types_Theme)

        Evergreen.V6.Types.TBNoop ->
            Evergreen.V7.Types.TBNoop


migrate_Types_ToFrontend : Evergreen.V6.Types.ToFrontend -> Evergreen.V7.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V6.Types.LeftSideRatioNewValue p0 p1 ->
            Evergreen.V7.Types.LeftSideRatioNewValue p0 p1

        Evergreen.V6.Types.RightSideRatioNewValue p0 p1 ->
            Evergreen.V7.Types.RightSideRatioNewValue p0 p1

        Evergreen.V6.Types.RangeNewValue p0 p1 p2 p3 ->
            Evergreen.V7.Types.RangeNewValue p0 p1 p2 p3

        Evergreen.V6.Types.AvatarScaleNewValue p0 p1 ->
            Evergreen.V7.Types.AvatarScaleNewValue p0 p1

        Evergreen.V6.Types.FankadeliSideNewValue p0 p1 p2 p3 ->
            Evergreen.V7.Types.FankadeliSideNewValue (p0 |> migrate_Types_Side) p1 p2 p3

        Evergreen.V6.Types.ResetRatiosNewValue p0 p1 p2 ->
            Evergreen.V7.Types.ResetRatiosNewValue p0 p1 p2

        Evergreen.V6.Types.ThemeNewValue p0 p1 ->
            Evergreen.V7.Types.HomeThemeNewValue (p0 |> migrate_Types_Theme) p1

        Evergreen.V6.Types.BackendNewValues p0 p1 ->
            Evergreen.V7.Types.BackendNewValues (p0 |> migrate_Types_BackendModel) p1

        Evergreen.V6.Types.TFNoop ->
            Evergreen.V7.Types.TFNoop
