module Evergreen.Migrate.V9 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V7.Types
import Evergreen.V9.Types
import Lamdera.Migrations exposing (..)


frontendModel : Evergreen.V7.Types.FrontendModel -> ModelMigration Evergreen.V9.Types.FrontendModel Evergreen.V9.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V7.Types.BackendModel -> ModelMigration Evergreen.V9.Types.BackendModel Evergreen.V9.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V7.Types.FrontendMsg -> MsgMigration Evergreen.V9.Types.FrontendMsg Evergreen.V9.Types.FrontendMsg
frontendMsg old =
    MsgUnchanged


toBackend : Evergreen.V7.Types.ToBackend -> MsgMigration Evergreen.V9.Types.ToBackend Evergreen.V9.Types.BackendMsg
toBackend old =
    MsgUnchanged


backendMsg : Evergreen.V7.Types.BackendMsg -> MsgMigration Evergreen.V9.Types.BackendMsg Evergreen.V9.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V7.Types.ToFrontend -> MsgMigration Evergreen.V9.Types.ToFrontend Evergreen.V9.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V7.Types.BackendModel -> Evergreen.V9.Types.BackendModel
migrate_Types_BackendModel old =
    { leftSideRatio = old.leftSideRatio
    , rightSideRatio = old.rightSideRatio
    , range = old.range
    , avatarScale = old.avatarScale
    , fankadeliSide = old.fankadeliSide |> migrate_Types_Side
    , homeTheme = old.homeTheme |> migrate_Types_Theme
    , adminTheme = old.adminTheme |> migrate_Types_Theme
    }


migrate_Types_Side : Evergreen.V7.Types.Side -> Evergreen.V9.Types.Side
migrate_Types_Side old =
    case old of
        Evergreen.V7.Types.Left ->
            Evergreen.V9.Types.Left

        Evergreen.V7.Types.Right ->
            Evergreen.V9.Types.Right


migrate_Types_Theme : Evergreen.V7.Types.Theme -> Evergreen.V9.Types.Theme
migrate_Types_Theme old =
    case old of
        Evergreen.V7.Types.Light ->
            Evergreen.V9.Types.Light

        Evergreen.V7.Types.Dark ->
            Evergreen.V9.Types.Dark


migrate_Types_ToFrontend : Evergreen.V7.Types.ToFrontend -> Evergreen.V9.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V7.Types.LeftSideRatioNewValue p0 p1 ->
            Evergreen.V9.Types.LeftSideRatioNewValue p0

        Evergreen.V7.Types.RightSideRatioNewValue p0 p1 ->
            Evergreen.V9.Types.RightSideRatioNewValue p0

        Evergreen.V7.Types.RangeNewValue p0 p1 p2 p3 ->
            Evergreen.V9.Types.RangeNewValue p0 p1 p2

        Evergreen.V7.Types.AvatarScaleNewValue p0 p1 ->
            Evergreen.V9.Types.AvatarScaleNewValue p0

        Evergreen.V7.Types.FankadeliSideNewValue p0 p1 p2 p3 ->
            Evergreen.V9.Types.FankadeliSideNewValue (p0 |> migrate_Types_Side) p1 p2

        Evergreen.V7.Types.ResetRatiosNewValue p0 p1 p2 ->
            Evergreen.V9.Types.ResetRatiosNewValue p0 p1

        Evergreen.V7.Types.HomeThemeNewValue p0 p1 ->
            Evergreen.V9.Types.HomeThemeNewValue (p0 |> migrate_Types_Theme)

        Evergreen.V7.Types.AdminThemeNewValue p0 p1 ->
            Evergreen.V9.Types.AdminThemeNewValue (p0 |> migrate_Types_Theme)

        Evergreen.V7.Types.BackendNewValues p0 p1 ->
            Evergreen.V9.Types.BackendNewValues (p0 |> migrate_Types_BackendModel)

        Evergreen.V7.Types.IsAdminVisibleOnHomePageNewValue p0 ->
            Evergreen.V9.Types.IsAdminVisibleOnHomePageNewValue p0

        Evergreen.V7.Types.TFNoop ->
            Evergreen.V9.Types.TFNoop
